server:
  port: 8080

security:
  jwt:
    secret: "CAMBIARESTACLAVESUPERLARGADE32CHARSMINIMO!!"

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: catalog
          uri: http://catalog-service:8082
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: orders
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

  #  configuraciones
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: null