server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://catalog-db:5432/catalogdb
    username: reto
    password: reto
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:reto}
    password: ${RABBITMQ_PASSWORD:reto}

management:
  endpoints:
    web:
      exposure:
        include: health,info
