server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://orders-db:5432/ordersdb
    username: reto
    password: reto
  jpa:
    hibernate:
      ddl-auto: update
catalog:
  service:
    url: http://catalog-service:8082
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: reto
    password: reto

management:
  endpoints:
    web:
      exposure:
        include: health,info
