server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://orders-db:5432/ordersdb
    username: reto
    password: reto
  jpa:
    hibernate:
      ddl-auto: update
catalog:
  service:
    url: http://catalog-service:8082
management:
  endpoints:
    web:
      exposure:
        include: health,info
